# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# version: 2 refers to goreleaser config format, not your app version
version: 2

project_name: dbsurf

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

nfpms:
  - id: dbsurf
    package_name: dbsurf
    vendor: jdtoombs
    homepage: "https://github.com/jdtoombs/dbsurf"
    maintainer: "jdtoombs <jdtoombs@users.noreply.github.com>"
    description: "TUI database explorer with vim-style navigation"
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

brews:
  - name: dbsurf
    repository:
      owner: jdtoombs
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/jdtoombs/dbsurf"
    description: "TUI database explorer with vim-style navigation"
    license: "MIT"
    install: |
      bin.install "dbsurf"
    test: |
      system "#{bin}/dbsurf", "--version"

release:
  prerelease: auto
  draft: false

publishers:
  - name: packagecloud
    ids:
      - dbsurf
    cmd: package_cloud push jonny-toombs/dbsurf/any/any {{ .ArtifactPath }}
    env:
      - PACKAGECLOUD_TOKEN={{ .Env.PACKAGECLOUD_TOKEN }}
